WITH CUSTOMERREVENUE AS (
SELECT  C.CUSTOMERID, 
        CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
        COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
        SUM(OI.QUANTITY * OI.UNITPRICE) AS REVENUE
	FROM COLLECTOR.CUSTOMERS C
	    JOIN COLLECTOR.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
	    JOIN COLLECTOR.ORDERITEMS OI ON O.ORDERID = OI.ORDERID
	GROUP BY C.CUSTOMERID, CUSTOMERNAME
	ORDER BY REVENUE DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT, REVENUE
FROM CUSTOMERREVENUE